// scripts/generate_karnataka_fpos.mjs
// Generates official SFAC Karnataka FPO dataset (125 genuine government-listed records)
import fs from 'fs';
import path from 'path';

const RAW_DATA = [
  {
    sNo: 1,
    state: "Karnataka",
    district: "Bidar",
    programme: "Pulses Programme",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Basveshwar Souhardha Multipurpose Co Operative Ltd.",
    legalForm: "Cooperative Society",
    registrationNumber: "3206-2013-14",
    registrationDate: "14.May.13",
    address: "At :Yarandagi, Basavkalyan to Gulbarga Road, Behind Homnabad Bus Stand, Yarandagi, Tal : Basvakalyan Dist: Bidar, Karnataka",
    contactPerson: "Mr. Gaurav Vats (RI)",
    contact: "9311309535",
    email: "gaurav@isapindia.org",
    majorCrops: ["Red gram", "Soybean", "Black gram", "Chickpea"]
  },
  {
    sNo: 2,
    state: "Karnataka",
    district: "Bidar",
    programme: "Pulses Programme",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Jai Javan Jai Kisanfarmers Organisation",
    legalForm: "Cooperative Society",
    registrationNumber: "BDR-S5-2013-14",
    registrationDate: "2.Apr.13",
    address: "Behind Mahesh Traders, Post Office : Santhpur, Tal : Aurad (B), Dist : Bidar, Karnataka",
    contactPerson: "Mr. Gaurav Vats (RI)",
    contact: "9311309535",
    email: "gaurav@isapindia.org",
    majorCrops: ["Red gram", "Soybean", "Black gram", "Chickpea"]
  },
  {
    sNo: 3,
    state: "Karnataka",
    district: "Bidar",
    programme: "Pulses Programme",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Jai Kisan Souhardha Multipurpose Co Operative Ltd.",
    legalForm: "Cooperative Society",
    registrationNumber: "UNB/V4/SS/RegNo/954/2012-13",
    registrationDate: "15.Sep.12",
    address: "Bidar Udgir Main Road, Halbarga, Tal : Bhalki, Dist : Bidar, Karnataka",
    contactPerson: "Mr. Gaurav Vats (RI)",
    contact: "9311309535",
    email: "gaurav@isapindia.org",
    majorCrops: ["Soybean", "Tur", "Gram"]
  },
  {
    sNo: 4,
    state: "Karnataka",
    district: "Bidar",
    programme: "Pulses Programme",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Mahatama Gandhi Farmers Organazation",
    legalForm: "Cooperative Society",
    registrationNumber: "BDR-S23-2013-14",
    registrationDate: "15.Apr.13",
    address: "Nandi Colony, Karnataka Electricity Board Road, Bidar, Tal & Dist : Bidar, Karnataka",
    contactPerson: "Mr. Gaurav Vats (RI)",
    contact: "9311309535",
    email: "gaurav@isapindia.org",
    majorCrops: ["Red gram", "Soybean", "Black gram", "Chickpea"]
  },
  {
    sNo: 5,
    state: "Karnataka",
    district: "Bidar",
    programme: "Pulses Programme",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Sri Basaveshwar Farmers Organisation",
    legalForm: "Cooperative Society",
    registrationNumber: "BDR-S8-2013-14",
    registrationDate: "2.Apr.13",
    address: "Opp. KSRTC Bus Stand Main Road Homnabad, Tal : Humnabad, Dist : Bidar, Karnataka",
    contactPerson: "Mr. Gaurav Vats (RI)",
    contact: "9311309535",
    email: "gaurav@isapindia.org",
    majorCrops: ["Tur", "Soybean", "Green Gram"]
  },
  {
    sNo: 6,
    state: "Karnataka",
    district: "Kalaburagi (Gulbarga)",
    programme: "Pulses Programme",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Balabhim Sena Farmer Producer Company Ltd",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2013PTC071691",
    registrationDate: "5.Nov.13",
    address: "At : Ribbanpalli, Opp. Anganwadi, Tal : Sedam, Dist: Kalaburagi, Karnataka",
    contactPerson: "Mr. Baskar (RI)",
    contact: "08088423123",
    email: "baskar@vrutti.org",
    majorCrops: ["Gram", "Tur", "Groundnut"]
  },
  {
    sNo: 7,
    state: "Karnataka",
    district: "Kalaburagi (Gulbarga)",
    programme: "Pulses Programme",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Kagina Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2013PTC071485",
    registrationDate: "18.Oct.13",
    address: "At : Kukunda, Near Nag Lingeshwar Temple, Tal : Sedam, Dist : Kalaburagi, Karnataka",
    contactPerson: "Mr. Baskar",
    contact: "08088423123",
    email: "baskar@vrutti.org",
    majorCrops: ["Tur", "Gram", "Green Gram"]
  },
  {
    sNo: 8,
    state: "Karnataka",
    district: "Kalaburagi (Gulbarga)",
    programme: "Pulses Programme",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Krishikabandhu Farmer Producer Company Ltd",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2014PTC072865",
    registrationDate: "3.Jan.14",
    address: "1/45 Shant Lingeshwar Mart Complex, Dharmapur, Tal : Aland, Dist : Kalaburagi, Karnataka",
    contactPerson: "Mr. Baskar",
    contact: "08088423123",
    email: "baskar@vrutti.org",
    majorCrops: ["Tur", "Gram", "Sunflower"]
  },
  {
    sNo: 9,
    state: "Karnataka",
    district: "Kalaburagi (Gulbarga)",
    programme: "Pulses Programme",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Nandhi Farmer Producer Company Ltd",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2014PTC073150",
    registrationDate: "21.Jan.14",
    address: "At & Po : Kirange, Tal & Dist : Kalaburagi, Karnataka",
    contactPerson: "Mr. Baskar",
    contact: "08088423123",
    email: "baskar@vrutti.org",
    majorCrops: ["Tur", "Gram", "Jowar"]
  },
  {
    sNo: 10,
    state: "Karnataka",
    district: "Kalaburagi (Gulbarga)",
    programme: "Pulses Programme",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Nisarga Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01400KA2013PTC071625",
    registrationDate: "31.Oct.13",
    address: "258, Near Gram Panchyat Office, Vil: Munnalli, Tal: Aland, Dist: Kalaburagi, Karnataka",
    contactPerson: "Mr. Baskar",
    contact: "08088423123",
    email: "baskar@vrutti.org",
    majorCrops: ["Tur", "Gram", "Sunflower"]
  },
  {
    sNo: 11,
    state: "Karnataka",
    district: "Kalaburagi (Gulbarga)",
    programme: "Pulses Programme",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Rohini Krishikara Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2013PTC071774",
    registrationDate: "18.Nov.13",
    address: "1/45, Dharmapur Village, Kalaburagi-525228, Karnataka",
    contactPerson: "Mr. Baskar",
    contact: "08088423123",
    email: "baskar@vrutti.org",
    majorCrops: ["Tur", "Banana"]
  },
  {
    sNo: 12,
    state: "Karnataka",
    district: "Vijayapura (Bijapur)",
    programme: "Pulses Programme",
    resourceInstitution: "Access Livelihoods Consulting India",
    fpoName: "Devara Hippargi Farmer Services Producer Company Ltd",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2014PTC073137",
    registrationDate: "21.Jan.14",
    address: "At : Devarhippargi, Near Ambedkar Circle, Tal : Sindagi, Dist : Vijayapura, Sindagi-586120, Karnataka",
    contactPerson: "Mr. Bala Subramaniam",
    contact: "07702220343",
    email: "info@alcindia.org",
    majorCrops: ["Tur", "Gram", "Jowar"]
  },
  {
    sNo: 13,
    state: "Karnataka",
    district: "Vijayapura (Bijapur)",
    programme: "Pulses Programme",
    resourceInstitution: "Access Livelihoods Consulting India",
    fpoName: "Jalwad Farmer Services Producer Company Ltd",
    legalForm: "Producer Company",
    registrationNumber: "U01400KA2013PTC072632",
    registrationDate: "20.Dec.13",
    address: "H.No. 547, Jalwad, Tal : Sindgi, Dist : Vijayapura, Karnataka",
    contactPerson: "Mr. Bala Subramaniam",
    contact: "07702220343",
    email: "info@alcindia.org",
    majorCrops: ["Tur", "Maize", "Gram"]
  },
  {
    sNo: 14,
    state: "Karnataka",
    district: "Vijayapura (Bijapur)",
    programme: "Pulses Programme",
    resourceInstitution: "Access Livelihoods Consulting India",
    fpoName: "Kalkeri Farmers Services Producer Company Ltd",
    legalForm: "Producer Company",
    registrationNumber: "U01400KA2013PTC072471",
    registrationDate: "18.Dec.13",
    address: "H.No. 538, Ashki, Tal : Sindagi, Dist : Vijayapura, Karnataka",
    contactPerson: "Mr. Bala Subramaniam",
    contact: "07702220343",
    email: "info@alcindia.org",
    majorCrops: ["Tur", "Jowar", "Wheat"]
  },
  {
    sNo: 15,
    state: "Karnataka",
    district: "Raichur",
    programme: "National Demonstration Project -NFSM",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Sri Budi Basweshwara Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01400KA2016PTC085136",
    registrationDate: "07.Jan.16",
    address: "House No.-18B, Village- Khanpur, Block- Devodurga, Distt.- Raichur, Devodurga-584113, Karnataka",
    contactPerson: "Mr. Rajeshekar Patil",
    contact: "8904175493",
    email: "rajashekharpatil3@gmail.com",
    majorCrops: ["Red Gram", "Green Gram"]
  },
  {
    sNo: 16,
    state: "Karnataka",
    district: "Raichur",
    programme: "National Demonstration Project -NFSM",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Sri Sharanabasaveshwara Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2015PTC084931",
    registrationDate: "20.Dec.15",
    address: "C/o Syed Usman Sab, H. No. 28, Village- Kagpal, Post- Kagpal, Near Basavanna Temple, Taluq- Manvi, Manvi, Raichur, Karnataka, 584118",
    contactPerson: "Mr. Vishwanath",
    contact: "9980810805",
    email: "Not available",
    majorCrops: ["Red Gram", "Green Gram", "Soybean"]
  },
  {
    sNo: 17,
    state: "Karnataka",
    district: "Raichur",
    programme: "National Demonstration Project -NFSM",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Amareshwara Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2016PTC095875",
    registrationDate: "22.Aug.16",
    address: "C/o Basappa S/o Pakirappa, Property no.- 42/03, Village/Post: Hirenaganur, Taluq- Lingasugur, Hirenaganur, Raichur, Karnataka, 584115",
    contactPerson: "Mr. Hanumesh Nayak",
    contact: "9972214887",
    email: "hanunayakktl@gmail.com",
    majorCrops: ["Red Gram", "Green Gram"]
  },
  {
    sNo: 18,
    state: "Karnataka",
    district: "Raichur",
    programme: "National Demonstration Project -NFSM",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Raichur Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2016PTC093905",
    registrationDate: "06.Jun.16",
    address: "C/o G. Yallappa Nayak, H. No. 28/2, Village & Post- Gonal, Vaya- Yaramaras, Taluq- Raichur, Raichur-584134, Karnataka",
    contactPerson: "Mr. Basavaraj",
    contact: "9449976207",
    email: "basava.msk@gmail.com",
    majorCrops: ["Red Gram", "Green Gram", "Soybean"]
  },
  {
    sNo: 19,
    state: "Karnataka",
    district: "Raichur",
    programme: "National Demonstration Project -NFSM",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Kankalayami Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01409KA2016PTC093929",
    registrationDate: "07.Jun.16",
    address: "C/o Mallappa, H. No.- 24, Village- Gudadunal, Post- Medanapur, Taluq- Lingasugur, Lingasugur, Raichur, Karnataka, 584115",
    contactPerson: "Mr Amresh",
    contact: "9008301765",
    email: "Not available",
    majorCrops: ["Red Gram", "Green Gram", "Soybean"]
  },
  {
    sNo: 20,
    state: "Karnataka",
    district: "Yadgir",
    programme: "National Demonstration Project -NFSM",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Punarvasu Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086821",
    registrationDate: "09.Mar.16",
    address: "15/1, Main Bazar, TQ-Shorapur, Dist- Yadgir, Naganoor- 585216, Karnataka",
    contactPerson: "Mr. Manjunath Heera",
    contact: "9008313018",
    email: "Not available",
    majorCrops: ["Tur", "Paddy"]
  },
  {
    sNo: 21,
    state: "Karnataka",
    district: "Yadgir",
    programme: "National Demonstration Project -NFSM",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Bhima Teera Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01400KA2016PTC087241",
    registrationDate: "24.Mar.16",
    address: "No. 3-9, At/Post- Alipur, TQ and Dist- Yadgir, Yadgir- 585202, Karnataka",
    contactPerson: "Mr. Nijaguna Kannalli",
    contact: "9902623349",
    email: "Not available",
    majorCrops: ["Groundnut", "Tur", "Green gram"]
  },
  {
    sNo: 22,
    state: "Karnataka",
    district: "Kalaburagi (Gulbarga)",
    programme: "National Demonstration Project -NFSM",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Nrupatunga Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01409KA2016PTC094735",
    registrationDate: "05.Jul.16",
    address: "No. 1/6, Vaccha, Vaccha, Chitapur, Kalaburagi, Karnataka, 585317",
    contactPerson: "Mr. Nagendra Ankad",
    contact: "9880624553",
    email: "Not available",
    majorCrops: ["Red gram", "Bengal Gram"]
  },
  {
    sNo: 23,
    state: "Karnataka",
    district: "Yadgir",
    programme: "National Demonstration Project -NFSM",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Bhagyodaya Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2016PTC094708",
    registrationDate: "05.Jul.16",
    address: "1-24 AT Rabbanhalli, TQ: Shahapur, DT: Yadgir, Rajapur, Karnataka, 585309",
    contactPerson: "Mr. Mahntayya Swamy",
    contact: "8310158171",
    email: "Not available",
    majorCrops: ["Paddy", "Red gram"]
  },
  {
    sNo: 24,
    state: "Karnataka",
    district: "Kalaburagi (Gulbarga)",
    programme: "National Demonstration Project -NFSM",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Kayaka Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01400KA2016PTC093890",
    registrationDate: "04.Jun.16",
    address: "Plot No.7-54, At/Post-Hebbal, Chittapur, Kalaburagi, Karnataka, 585323",
    contactPerson: "Mr. Vikram Nimbhal",
    contact: "9480928542",
    email: "Not available",
    majorCrops: ["Red gram", "Bengal gram"]
  },
  {
    sNo: 25,
    state: "Karnataka",
    district: "Davanagere",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Shanthi Sagara Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01400KA2016PTC086459",
    registrationDate: "24.Feb.16",
    address: "Devarahalli, At post Channagiri Taluk, Davanagere dist, 577215, Karnataka",
    contactPerson: "Mr. Avinash",
    contact: "9743392761",
    email: "Channagirifpo@gmail.com",
    majorCrops: ["Mango", "Coconut"]
  },
  {
    sNo: 26,
    state: "Karnataka",
    district: "Chitradurga",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Sirigere Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086564",
    registrationDate: "29.Feb.16",
    address: "H. No. 25, Sirigere-1, Sirigere- 577541, Karnataka",
    contactPerson: "Mr. Rajappa",
    contact: "8105616769",
    email: "sirigerehfpcl@gmail.com",
    majorCrops: ["Pomegranate", "Mango"]
  },
  {
    sNo: 27,
    state: "Karnataka",
    district: "Tumakuru",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Hemavathi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086592",
    registrationDate: "5.Mar.16",
    address: "H.No. 155/A, Tyagatore, Gubbi- 572223, Karnataka",
    contactPerson: "Mr. Chandrashekar",
    contact: "9740161407",
    email: "gubbifpo@gmail.com",
    majorCrops: ["Banana", "Tomato"]
  },
  {
    sNo: 28,
    state: "Karnataka",
    district: "Chikkaballapura",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Amaranarayana Horticulture Farmers Producer Company",
    legalForm: "Producer Company",
    registrationNumber: "U01122KA2016PTC086207",
    registrationDate: "16.Feb.16",
    address: "H.No. 160, Madikere, Chintamani Taluk, Chikkaballapur District- 563125, Karnataka",
    contactPerson: "Mr. Reddy",
    contact: "9448118949",
    email: "chintamanifpo@gmail.com",
    majorCrops: ["Mango", "Tomato"]
  },
  {
    sNo: 29,
    state: "Karnataka",
    district: "Chikkaballapura",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Sadaliamma Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01122KA2016PTC086206",
    registrationDate: "16.Feb.16",
    address: "H.No. 128, Sadaku, Sidlaghatta Taluk, Chikkaballapur District- 562104, Karnataka",
    contactPerson: "Anitha",
    contact: "9008776778",
    email: "shidlaghattafpo@gmail.com",
    majorCrops: ["Onion", "Tomato"]
  },
  {
    sNo: 30,
    state: "Karnataka",
    district: "Kolar",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Masthi Venkatesh Lyengar Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01400KA2016PTC086414",
    registrationDate: "23.Feb.16",
    address: "H.No.100, Rajenahalli, Malur- 563137, Karnataka",
    contactPerson: "Mr. Venaktappa",
    contact: "8904996522",
    email: "rajenahallirajenahalli@gmail.com",
    majorCrops: ["Tomato", "Cabbage"]
  },
  {
    sNo: 31,
    state: "Karnataka",
    district: "Kolar",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Shri Kadandaramaswamy Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01122KA2016PTC086208",
    registrationDate: "16.Feb.16",
    address: "H. No. 148, Yeldur, Srinivaspur- 563138, Karnataka",
    contactPerson: "Mr. Manjunath",
    contact: "7892677403",
    email: "kodhandaramaswamyhfpcl@gmail.com",
    majorCrops: ["Mango", "Tomato"]
  },
  {
    sNo: 32,
    state: "Karnataka",
    district: "Kolar",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Shri Vinayaka Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086413",
    registrationDate: "23.Feb.16",
    address: "H.No. 82/1A, Tayalur, Mulbagal- 563136, Karnataka",
    contactPerson: "Mr. Vishwanath",
    contact: "9740457705",
    email: "mulbagalfpo@gmai.com",
    majorCrops: ["Tomato", "Mango"]
  },
  {
    sNo: 33,
    state: "Karnataka",
    district: "Bengaluru Rural",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Shri Venegopalaswamy Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086178",
    registrationDate: "15.Feb.16",
    address: "H.No. 57, Doddadenahalli, Hosakote, Bangalore Rural-562114, Karnataka",
    contactPerson: "Mr. Venkataramana",
    contact: "8904996522",
    email: "hoskotefpo@gmail.com",
    majorCrops: ["Potato", "Tomato"]
  },
  {
    sNo: 34,
    state: "Karnataka",
    district: "Davanagere",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Devanagari Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC085985",
    registrationDate: "10.Feb.16",
    address: "H. No. 153, Huchavvanahalli, Devanagere Taluk, Devanagere District, Devanagere- 577528, Karnataka",
    contactPerson: "Mr. Shiva Kumar",
    contact: "831096886",
    email: "devanagarifpo@gmail.com",
    majorCrops: ["Arecanut", "Pomegranate"]
  },
  {
    sNo: 35,
    state: "Karnataka",
    district: "Chitradurga",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Shri Ramalingeshwara Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086563",
    registrationDate: "29.Feb.16",
    address: "H.No.143, Kanguvalli-1, Hosadurga- 577515, Karnataka",
    contactPerson: "Mr. Mounesh Acharya",
    contact: "8970004229",
    email: "hosadurgafpo@gmail.com",
    majorCrops: ["Papaya", "Pomegranate"]
  },
  {
    sNo: 36,
    state: "Karnataka",
    district: "Davanagere",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Kondukuri Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC087274",
    registrationDate: "24.Mar.16",
    address: "463/1, Asagodu, Jagalur- 577513, Karnataka",
    contactPerson: "Mr. Rudresh",
    contact: "8722632273",
    email: "jagalurfpo@gmail.com",
    majorCrops: ["Arecanut", "Tomato"]
  },
  {
    sNo: 37,
    state: "Karnataka",
    district: "Tumakuru",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Gadinadu Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01122KA2016PTC086201",
    registrationDate: "16.Feb.16",
    address: "H.No.146, Barajure, Sira Taluk- 572113, Karnataka",
    contactPerson: "Mr. Shivanna",
    contact: "7975064690",
    email: "sirafpo@gmail.com",
    majorCrops: ["Pomegranate", "Tomato"]
  },
  {
    sNo: 38,
    state: "Karnataka",
    district: "Tumakuru",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Pavagada Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2016PTC094012",
    registrationDate: "10.Jun.16",
    address: "D.No. 150, Mangalavada, Pavagada Taluk, Tumakuru, Karnataka, 572116",
    contactPerson: "Mr. Vinod",
    contact: "9900761760",
    email: "pavagadafpo1@gmail.com",
    majorCrops: ["Not available"]
  },
  {
    sNo: 39,
    state: "Karnataka",
    district: "Bengaluru Rural",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Gangadevi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC087275",
    registrationDate: "24.Mar.16",
    address: "H.No. 45, Kaggalahalli Village, Devanahalli Taluk-562123, Karnataka",
    contactPerson: "Mr. Shashidhar",
    contact: "8618620778",
    email: "Not available",
    majorCrops: ["Flowers", "Potato"]
  },
  {
    sNo: 40,
    state: "Karnataka",
    district: "Chikkamagaluru",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Chandra Drona India Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2015PTC082628",
    registrationDate: "5.Sep.15",
    address: "H.No. 198, Rashmi Nilaya, Near Gowramma Temple, Lakya- 577168, Karnataka",
    contactPerson: "Mr. Rachan",
    contact: "9591252190",
    email: "Not available",
    majorCrops: ["Tomato", "Potato", "Beans", "Green Chilli"]
  },
  {
    sNo: 41,
    state: "Karnataka",
    district: "Ballari",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Tungabhadra Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086650",
    registrationDate: "4.Mar.16",
    address: "No. 412, 15th Ward, Near Chandra Mouleswara Temple, Amravati, Hospet Taluk, Ballari- 583201, Karnataka",
    contactPerson: "Mr. Bharath Kumar.V",
    contact: "9945568578",
    email: "Not available",
    majorCrops: ["Banana", "Dry Chilli", "Green chilli", "Tomato", "Onion"]
  },
  {
    sNo: 42,
    state: "Karnataka",
    district: "Bidar",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Kayakalpa Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086716",
    registrationDate: "7.Mar.16",
    address: "Basavarj S/O Raghuveer Kanshetty, Near Bus Stand, Indranagar, Hudugi, Humnabad Taluk, Bidar- 585329, Karnataka",
    contactPerson: "Mr. Tanaji",
    contact: "9902601459",
    email: "Not available",
    majorCrops: ["Ginger", "Mango", "Tomato", "Grapes", "Banana"]
  },
  {
    sNo: 43,
    state: "Karnataka",
    district: "Hassan",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Sri Manjunatheshwara Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC087058",
    registrationDate: "18.Mar.16",
    address: "Prashanth N. K S/O B. R Krishnamurthy, Opposite Govt, Junior College, Premanagara, Nuggehalli Post, Channarayapatna- 573131, Karnataka",
    contactPerson: "Mr. Shrikant",
    contact: "9620492245",
    email: "Not available",
    majorCrops: ["Coconut", "Tomato", "Green Chilli", "Banana", "Potato", "Ginger"]
  },
  {
    sNo: 44,
    state: "Karnataka",
    district: "Dharwad",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Kayaka Yogi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086696",
    registrationDate: "7.Mar.16",
    address: "C/O Basavaraj Shivapur, Near Air-Tech Factory, P. B Road, Dharwad- 580005, Karnataka",
    contactPerson: "Mr. Fakeerappa Vasanth Bangolli",
    contact: "9164036283",
    email: "Not available",
    majorCrops: ["Mango", "Onion", "Dry chilli", "Tomato", "Banana"]
  },
  {
    sNo: 45,
    state: "Karnataka",
    district: "Gadag",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Puttarajagawayi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086863",
    registrationDate: "11.Mar.16",
    address: "Vijay Kumar A. Kittali Shri Tulasegere Dhama, behind P & T Quarters, Kareyamma Kallu Bhadavani, Gadag- 582101, Karnataka",
    contactPerson: "Mr. Satish",
    contact: "9481565980",
    email: "Not available",
    majorCrops: ["Dry Chilli", "Onion", "Mango", "Green chilli", "Chrysanthemum"]
  },
  {
    sNo: 46,
    state: "Karnataka",
    district: "Haveri",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Kumareshwar Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086813",
    registrationDate: "9.Mar.16",
    address: "C/o Shankar B Benageri, Havanagi, Hanagal, Hanagal- 581102, Karnataka",
    contactPerson: "Chitra AM",
    contact: "8431437128",
    email: "Not available",
    majorCrops: ["Mango", "Dry Chilli", "Banana", "Onion", "Ginger", "Arecanut"]
  },
  {
    sNo: 47,
    state: "Karnataka",
    district: "Haveri",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Bhootayi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086431",
    registrationDate: "24.Feb.16",
    address: "Vinayak Vaibhava Laxmi Park, Near Saibaba Temple, Haveri- 581110, Karnataka",
    contactPerson: "Mr. Prakash Pati",
    contact: "9164684889",
    email: "Not available",
    majorCrops: ["Guava", "Mango", "Banana", "Green Chilli", "Onion"]
  },
  {
    sNo: 48,
    state: "Karnataka",
    district: "Dharwad",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Uluva Yogi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086718",
    registrationDate: "7.Mar.16",
    address: "C/o Manjunath Indi, Katnur Post, Hubli Taluk, Dharwad- 580024, Karnataka",
    contactPerson: "Mr. Suresh",
    contact: "8951379752",
    email: "Not available",
    majorCrops: ["Dry Chilli", "Onion", "Mango", "Tomato", "Banana"]
  },
  {
    sNo: 49,
    state: "Karnataka",
    district: "Kalaburagi (Gulbarga)",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Negilayogi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086607",
    registrationDate: "3.Mar.16",
    address: "1/1/53, Umarga Road, Iswara Nagar, Aland, Kalaburagi- 585314, Karnataka",
    contactPerson: "Mr. Shivashankar Chincholi",
    contact: "9900829550",
    email: "Not available",
    majorCrops: ["Banana", "Green Chilli", "Onion", "Tomato", "Mango", "Pomegranate"]
  },
  {
    sNo: 50,
    state: "Karnataka",
    district: "Koppal",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Abhinavashree Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086747",
    registrationDate: "8.Mar.16",
    address: "Sanganagouda Patil, Kalakaleshwara Complex, B. T Nagar, Opp Hudaco Colony, Hospet Road, Koppal- 583231, Karnataka",
    contactPerson: "Mr. Srishila pattar",
    contact: "9900256344",
    email: "Not available",
    majorCrops: ["Tomato", "Green Chilli", "Mango", "Banana", "Onion"]
  },
  {
    sNo: 51,
    state: "Karnataka",
    district: "Koppal",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Kapilathirtha Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086793",
    registrationDate: "9.Mar.16",
    address: "No. 17/5549, Basavanilaya, Behind Buttibasaveshwar, Temple, B.B Nagar, Kushtagi Taluk, Koppal- 584121, Karnataka",
    contactPerson: "Mr. Raghav",
    contact: "8904789732",
    email: "Not available",
    majorCrops: ["Pomegranate", "Mango", "Citrus", "Tomato", "Onion"]
  },
  {
    sNo: 52,
    state: "Karnataka",
    district: "Kodagu",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Shri Bhagandeshwara Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086695",
    registrationDate: "7.Mar.16",
    address: "S/O Medappa, Padakallu village, Padakallu Post, Bhagamandala Hobli, Madikeri- 571247, Karnataka",
    contactPerson: "Mr. Benny",
    contact: "9481331077",
    email: "Not available",
    majorCrops: ["Pepper", "Arecanut", "Banana", "Citrus"]
  },
  {
    sNo: 53,
    state: "Karnataka",
    district: "Koppal",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Dayasagar Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC087153",
    registrationDate: "22.Mar.16",
    address: "Nalareddy S/O Mohanreddy Guni, House No. 1/9, Near Hanuman Temple, Gunni Colony At Post Gajarkot, Yadgir- 585214, Karnataka",
    contactPerson: "Mr. Santosh",
    contact: "9008809034",
    email: "Not available",
    majorCrops: ["Mango", "Onion", "Tomato", "Brinjal", "Banana"]
  },
  {
    sNo: 54,
    state: "Karnataka",
    district: "Hassan",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Yagachi Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086856",
    registrationDate: "10.Mar.16",
    address: "C/o H.M. Chandrashekar, Hoyasala Street, Village- Neharu Nagara, Taluq- Beluru, Neharu Nagara-573115, Karnataka",
    contactPerson: "Mr. Naveen",
    contact: "9739855666",
    email: "Not available",
    majorCrops: ["Coconut", "Potato", "Green Chilli", "Tomato", "Ginger", "Beans", "Gourds"]
  },
  {
    sNo: 55,
    state: "Karnataka",
    district: "Udupi",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Karkala Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086676",
    registrationDate: "4.Mar.16",
    address: "#7-152, Nagashree, Ambadekallu Road, Nitte, Karkala- 574110, Karnataka",
    contactPerson: "Mr. Shalini",
    contact: "9448725305",
    email: "Not available",
    majorCrops: ["Coconut", "Arecanut", "Vegetables"]
  },
  {
    sNo: 56,
    state: "Karnataka",
    district: "Vijayapura (Bijapur)",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Shri Shanteshwar Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086639",
    registrationDate: "3.Mar.16",
    address: "1033/k, Plot No. 53, Station Road, Indi, Indi- 586112, Karnataka",
    contactPerson: "Mr. Prakash Mallad",
    contact: "9880832526",
    email: "Not available",
    majorCrops: ["Grapes", "Lemon"]
  },
  {
    sNo: 57,
    state: "Karnataka",
    district: "Shivamogga",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Malnad Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086677",
    registrationDate: "4.Mar.16",
    address: "19-4, Chikkanelluru, Sagar- 577401, Karnataka",
    contactPerson: "Mr. Ramakrishna",
    contact: "9663836900",
    email: "Not available",
    majorCrops: ["Arecanut", "Pineapple", "Pepper", "Ginger", "Nutmeg"]
  },
  {
    sNo: 58,
    state: "Karnataka",
    district: "Bagalkot",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Jamkhandi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086591",
    registrationDate: "5.Mar.16",
    address: "H.No. 282, Todalabagi, Jamakhandi- 587301, Karnataka",
    contactPerson: "Mr. Sashikanth Vishnu Bhosle",
    contact: "9741499358",
    email: "Not available",
    majorCrops: ["Grapes", "Pomegranate"]
  },
  {
    sNo: 59,
    state: "Karnataka",
    district: "Shivamogga",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Shivamogga Thungabhadra Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086737",
    registrationDate: "8.Mar.16",
    address: "H.No. 192, Mallapura, Sowlanga, Shimoga- 577225, Karnataka",
    contactPerson: "Mr. Vinayak. V",
    contact: "8861094060",
    email: "Not available",
    majorCrops: ["Cereals", "Chilli", "Tomato"]
  },
  {
    sNo: 60,
    state: "Karnataka",
    district: "Chikkamagaluru",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Shree Guru Siddarameshwara Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086790",
    registrationDate: "9.Mar.16",
    address: "H.No. 99, Javoor Horahalli Village, Javoor Post, Tarikere, Chikmagalur- 577145, Karnataka",
    contactPerson: "Mr. Chethan",
    contact: "9108236698",
    email: "Not available",
    majorCrops: ["Onion"]
  },
  {
    sNo: 61,
    state: "Karnataka",
    district: "Dakshina Kannada",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Pingaara Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2016PTC093488",
    registrationDate: "23.May.16",
    address: "D.No. 5-651, Bobbekeri Vittal, Bantwal Taluk, Dakshina Kannada, Vittal, Dakshina Kannada- 574243, Karnataka",
    contactPerson: "Mr. Pradeep",
    contact: "9480253747",
    email: "Not available",
    majorCrops: ["Arecanut", "Jack Fruit"]
  },
  {
    sNo: 62,
    state: "Karnataka",
    district: "Dakshina Kannada",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Navachetana Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01122KA2016PTC093911",
    registrationDate: "6.Jun.16",
    address: "#106, Karaya Village & Post, Belthangady, Karaya, Dakshina Kannada- 574326, Karnataka",
    contactPerson: "Mr. Rajesh A.S",
    contact: "8722638840",
    email: "Not available",
    majorCrops: ["Arecanut", "Coconut"]
  },
  {
    sNo: 63,
    state: "Karnataka",
    district: "Bagalkot",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Kaladgi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086640",
    registrationDate: "3.Mar.16",
    address: "H.No. 1582/2, Kaladgi, Bagalkot-587204, Karnataka",
    contactPerson: "Mr. Javeed Jagur",
    contact: "9148377236",
    email: "Not available",
    majorCrops: ["Pomegranate", "Vegetables"]
  },
  {
    sNo: 64,
    state: "Karnataka",
    district: "Vijayapura (Bijapur)",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Sindagi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086738",
    registrationDate: "8.Mar.16",
    address: "4447, Kalmeshwar Nagar, Indi Road, Devara hipparagi, Sindagi- 586115, Karnataka",
    contactPerson: "Mr. Biradar",
    contact: "9901505607",
    email: "Not available",
    majorCrops: ["Grapes", "Pomegranate"]
  },
  {
    sNo: 65,
    state: "Karnataka",
    district: "Raichur",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Parisara Premi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01110KA2017PTC100300",
    registrationDate: "8.Feb.17",
    address: "H. No. 7-6-207/4, Near City Bus Stop, Vasavi Nagar, Raichur, Raichur- 584103, Karnataka",
    contactPerson: "Mr. Ramu",
    contact: "9964467775",
    email: "Not available",
    majorCrops: ["Fig", "Mango", "Pomegranate", "Red Gram", "Vegetables"]
  },
  {
    sNo: 66,
    state: "Karnataka",
    district: "Mandya",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Malavalli Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086842",
    registrationDate: "10.Mar.16",
    address: "#28/13, Kyathanahalli village, Malavalli - Poorigali main Road, Malavalli Taluk, Mandya Dist- 577001, Karnataka",
    contactPerson: "Mr Jagadeesh",
    contact: "9980050129",
    email: "Not available",
    majorCrops: ["Cabbage", "Onion", "Beans", "Tomato"]
  },
  {
    sNo: 67,
    state: "Karnataka",
    district: "Bengaluru Urban",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Anekal Horticulture Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086729",
    registrationDate: "8.Mar.16",
    address: "JFMC court opposite, Attibele Road, Anekal Town, Bengaluru Rural, 562106, Karnataka",
    contactPerson: "Mr Siddaraju",
    contact: "9448246723",
    email: "Not available",
    majorCrops: ["Tomato", "Cauliflower", "Beans"]
  },
  {
    sNo: 68,
    state: "Karnataka",
    district: "Ramanagara",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Srigripura Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01400KA2016PTC086899",
    registrationDate: "14.Mar.16",
    address: "No.295, 296 & 297, Srigripura post, Kudur, Magadi Taluk, Bengaluru- 560011, Karnataka",
    contactPerson: "Mr Lenkappa",
    contact: "9449508889",
    email: "Not available",
    majorCrops: ["Beans", "Bitter Gourd", "Mango"]
  },
  {
    sNo: 69,
    state: "Karnataka",
    district: "Ramanagara",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Gombenadu Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086870",
    registrationDate: "11.Mar.16",
    address: "Near bus stop, Akkuru village and post, Channapatna Taluk, Ramanagara Dist, 562138, Karnataka",
    contactPerson: "Ms. Susmita",
    contact: "9740705653",
    email: "Not available",
    majorCrops: ["Coconut", "Banana", "Beans", "Tomato"]
  },
  {
    sNo: 70,
    state: "Karnataka",
    district: "Bengaluru Rural",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Rajaghatta Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086862",
    registrationDate: "11.Mar.16",
    address: "Rajghatta village, Rajghatta Post, Doddaballapur Taluk, Bangalore Rural Dist - 561 203, Karnataka",
    contactPerson: "Ms. Chaitra",
    contact: "9743678248",
    email: "Not available",
    majorCrops: ["Beans", "Cauliflower", "Tomato", "Grapes"]
  },
  {
    sNo: 71,
    state: "Karnataka",
    district: "Mandya",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Honnakere Hobli Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086909",
    registrationDate: "14.Mar.16",
    address: "Brahammadevarahalli village, Honnakere Hobli, Nagamangala Taluk, Mandya Dist, Karnataka - 571 810",
    contactPerson: "Mr Krishna Murthy",
    contact: "9353081364",
    email: "Not available",
    majorCrops: ["Cabbage", "Onion", "Beans", "Tomato"]
  },
  {
    sNo: 72,
    state: "Karnataka",
    district: "Mysuru",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Hussainpura Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086946",
    registrationDate: "15.Mar.16",
    address: "Samudaya Bhavan Building, Near Society Building, Hussainpur, Hunsur taluk, Mysuru - 571103, Karnataka",
    contactPerson: "Ms Harshita",
    contact: "9620582804",
    email: "Not available",
    majorCrops: ["Beans", "Banana", "Cauliflower"]
  },
  {
    sNo: 73,
    state: "Karnataka",
    district: "Bengaluru Rural",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Tubugere Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC087255",
    registrationDate: "24.Mar.16",
    address: "Shop. No. 06 & 07, K.Ramaswamy Building, opp. Government Hospital, Tubugere, Doddaballapur Taluk, Bengaluru Rural - 561203, Karnataka",
    contactPerson: "Ms. Roopa",
    contact: "7338029625",
    email: "Not available",
    majorCrops: ["Beans", "Cabbage", "Tomato", "Carrot"]
  },
  {
    sNo: 74,
    state: "Karnataka",
    district: "Chamarajanagar",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Udigal Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086798",
    registrationDate: "9.Mar.16",
    address: "Jungerr No.6/3, Udigal village, Harave Hobli, Chamarajanagar - 571 313, Karnataka",
    contactPerson: "Mr. Shivaraudra",
    contact: "9886346793",
    email: "Not available",
    majorCrops: ["Chilli", "Tomato"]
  },
  {
    sNo: 75,
    state: "Karnataka",
    district: "Chamarajanagar",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Gundlupete Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01407KA2016PTC086812",
    registrationDate: "9.Mar.16",
    address: "TAPCMS Building, 1st Division, 2nd ward, Gundlupet Town, Chamarajanagar - 571111, Karnataka",
    contactPerson: "Mr. Mahendra",
    contact: "8183828558",
    email: "Not available",
    majorCrops: ["Coconut", "Potato", "Tomato", "Beans"]
  },
  {
    sNo: 76,
    state: "Karnataka",
    district: "Uttara Kannada",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Shri Madhukeshwar Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086806",
    registrationDate: "9.Mar.16",
    address: "No. 41, Andagi village, Banavasi, Sirsi, Karnataka",
    contactPerson: "Mr Yuvaraj",
    contact: "8105872028",
    email: "Not available",
    majorCrops: ["Pineapple", "Banana", "Ginger"]
  },
  {
    sNo: 77,
    state: "Karnataka",
    district: "Ramanagara",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Sangama Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01409KA2016PTC092941",
    registrationDate: "5.May.16",
    address: "I. Gollahalli village, Kanakapura, Ramanagara - 562119, Karnataka",
    contactPerson: "Mr. Keerthi",
    contact: "9964646323",
    email: "Not available",
    majorCrops: ["Tomato", "Mango", "Brinjal"]
  },
  {
    sNo: 78,
    state: "Karnataka",
    district: "Mysuru",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Varuna Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2016PTC092866",
    registrationDate: "3.May.16",
    address: "Varuna village & Post, Varuna Hobli, Mysuru - 570 010, Karnataka",
    contactPerson: "Mr Paramesh",
    contact: "9902081847",
    email: "Not available",
    majorCrops: ["Tomato", "Banana", "Coconut"]
  },
  {
    sNo: 79,
    state: "Karnataka",
    district: "Mandya",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Nanjanagud Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01409KA2016PTC093758",
    registrationDate: "31.May.16",
    address: "Shivkumar Residency Building, Mysuru - Rampura Main road, Hullahalli village, Nanjanagud Taluk, Mysuru - 571 314, Karnataka",
    contactPerson: "Mr. V N Murthy",
    contact: "9844596602",
    email: "Not available",
    majorCrops: ["Tomato", "Banana", "Coconut"]
  },
  {
    sNo: 80,
    state: "Karnataka",
    district: "Belagavi",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Shri Siddeshwar Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086805",
    registrationDate: "9.Mar.16",
    address: "Gavi Building, opposite Kakati Police Station, NH-4, Kakati, Dist- Belagavi, Karnataka",
    contactPerson: "Mr Mahesh S Havikatti",
    contact: "8722831228",
    email: "belagavifpo@gmail.com",
    majorCrops: ["Potato", "Cauliflower", "Cabbage", "Chilli", "Beans"]
  },
  {
    sNo: 81,
    state: "Karnataka",
    district: "Belagavi",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Nipani Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086679",
    registrationDate: "4.Mar.16",
    address: "At Post: Sounsalga, Taluka: Chikodi, Dist- Belagavi, 591241, Karnataka",
    contactPerson: "Mr. Vishal",
    contact: "9019915828",
    email: "Not available",
    majorCrops: ["Onion", "Banana", "Brinjal", "Cabbage", "Cauliflower"]
  },
  {
    sNo: 82,
    state: "Karnataka",
    district: "Belagavi",
    programme: "Special Project (Phase-I)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Yamakanmardi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01403KA2016PTC086712",
    registrationDate: "7.Mar.16",
    address: "S R Joshi Building, SR.No271A3 NH4 Dadabanhatti Above Ram Dhaba, Taluka Hukkeri, Belagavi Dist, Karnataka",
    contactPerson: "Mr. Balesh Pong",
    contact: "7619155516",
    email: "hukkerifpo@gmail.com",
    majorCrops: ["Ladies finger", "Cabbage", "Green Chilli", "Brinjal"]
  },
  {
    sNo: 83,
    state: "Karnataka",
    district: "Uttara Kannada",
    programme: "KSSDB",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Aghanashini Spice Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2016PTC096439",
    registrationDate: "14.Sep.16",
    address: "At Nanikatta, Po Tyagali, Tq Siddapur, Siddapur, Uttara Kannada, Karnataka, 581340",
    contactPerson: "Mr Darshan",
    contact: "9482348523",
    email: "Not available",
    majorCrops: ["Pepper", "Arecanut", "Cardamom"]
  },
  {
    sNo: 84,
    state: "Karnataka",
    district: "Dharwad",
    programme: "KSSDB",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Amarashiva Spices Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC100944",
    registrationDate: "28.Feb.17",
    address: "# 1122, Market Road, Sanshi, Kundagol (TQ), Dharwad (Dist), Dharwad- 581117, Karnataka",
    contactPerson: "Ms Jnaneswari",
    contact: "9742152522",
    email: "Not available",
    majorCrops: ["Pepper", "Arecanut", "Cardamom"]
  },
  {
    sNo: 85,
    state: "Karnataka",
    district: "Chitradurga",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Hombelaku Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC101732",
    registrationDate: "27.Mar.17",
    address: "#56, Hireyemmiganuru, Holalkere Taluk, Hireyemmiganure, Chitradurga, Karnataka, 577523",
    contactPerson: "Mr. Pradeepa CS",
    contact: "9743068215",
    email: "holalkerefpo@gmail.com",
    majorCrops: ["Mixed Vegetables"]
  },
  {
    sNo: 86,
    state: "Karnataka",
    district: "Kolar",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Moodalagiri Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01115KA2017PTC101735",
    registrationDate: "27.Mar.17",
    address: "Mulbagal Taluk, Gudipalli, Kolar District, Pin code 563132, Karnataka",
    contactPerson: "Mr. Soundarya CS",
    contact: "8861437037",
    email: "mulbagalnewfpo@gmail.com",
    majorCrops: ["Mango", "Mixed Vegetables", "Tomato"]
  },
  {
    sNo: 87,
    state: "Karnataka",
    district: "Chikkaballapura",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Cheluru Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC101384",
    registrationDate: "15.Mar.17",
    address: "#532, Cheluru, Bagepalli Taluk, Chikkaballapura District, Pin code - 563124, Karnataka",
    contactPerson: "Ms. Navita",
    contact: "9980301017",
    email: "fpobagepalli@gmail.com",
    majorCrops: ["Almond", "Mixed Vegetables"]
  },
  {
    sNo: 88,
    state: "Karnataka",
    district: "Davanagere",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Sri Uthsavamba Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01113KA2017PTC101690",
    registrationDate: "24.Mar.17",
    address: "Vill- Sindhisar, P.O- Amlighat, Davanagere, Karnataka",
    contactPerson: "Mr. Ranganath",
    contact: "8660307978",
    email: "uthsavambahfpcl@gmail.com",
    majorCrops: ["Mixed Vegetables"]
  },
  {
    sNo: 89,
    state: "Karnataka",
    district: "Davanagere",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Tirtharameswara Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01400KA2017PTC101839",
    registrationDate: "13.Mar.17",
    address: "#466/239/273B, Surahonne, Belaguthi, Honnali, Surahonne, Davanagere, Karnataka, 577225",
    contactPerson: "Ms. Kavya",
    contact: "9538975833",
    email: "thirtharameshwara2017@gmail.com",
    majorCrops: ["Mixed Vegetables"]
  },
  {
    sNo: 90,
    state: "Karnataka",
    district: "Ramanagara",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Arkavathi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC102297",
    registrationDate: "17.Apr.17",
    address: "#28/28/2, Kailancha, Ramanagara Taluk & District, Ramanagara, Karnataka, 562959",
    contactPerson: "Mr. Raju MR",
    contact: "9986872589",
    email: "arkavathyfpo@gmail.com",
    majorCrops: ["Mixed Vegetables"]
  },
  {
    sNo: 91,
    state: "Karnataka",
    district: "Davanagere",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Vishwabandhu Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC101705",
    registrationDate: "27.Mar.17",
    address: "H. NO. 113, Hebbalu Village, Davanagere Taluk, Hebbalu, Davanagere, Karnataka, 577556",
    contactPerson: "Mr. Rudresh",
    contact: "7760302806",
    email: "vishwabandhuhfpclhebbalu@gmail.com",
    majorCrops: ["Mixed Vegetables"]
  },
  {
    sNo: 92,
    state: "Karnataka",
    district: "Tumakuru",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Hebburu Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01114KA2017PTC107167",
    registrationDate: "13.Oct.17",
    address: "H. No. 1875/623, Hebbur, Tumakuru Taluk, Hebbur, Tumakuru, Karnataka, 572120",
    contactPerson: "Mr. Chandrashekar",
    contact: "9740161407",
    email: "heburfpo@gmail.com",
    majorCrops: ["Coconut", "Mixed Vegetables"]
  },
  {
    sNo: 93,
    state: "Karnataka",
    district: "Tumakuru",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Vrutti Livelihood Resource Center (VLRC)",
    fpoName: "Godekere Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01110KA2017PTC104706",
    registrationDate: "17.Jul.17",
    address: "Godekere, Shettikere Hobli, Chikkanayakanahalli Taluk, Godekere, Tumakuru, Karnataka, 572214",
    contactPerson: "Mr. Thippeswamy",
    contact: "7899161407",
    email: "godkerefpo@gmail.com",
    majorCrops: ["Coconut", "Mixed Vegetables"]
  },
  {
    sNo: 94,
    state: "Karnataka",
    district: "Belagavi",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Telasang Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01112KA2017PTC100882",
    registrationDate: "27.Feb.17",
    address: "Odeyar Home, At & Post: Kakamari, Athani (TQ), Belagavi (Dist), Belagavi, Karnataka, 591269",
    contactPerson: "Amoghsidda C Odeyar",
    contact: "0973921771",
    email: "amogha2017@gmail.com",
    majorCrops: ["Grapes", "Pomegranate"]
  },
  {
    sNo: 95,
    state: "Karnataka",
    district: "Mandya",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Kengal Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01110KA2017PTC100827",
    registrationDate: "23.Feb.17",
    address: "#63, Byrapattana, Eswara Temple Road, Channapatna, Bangalore Rural, Karnataka, 562160",
    contactPerson: "Ms Jyothi",
    contact: "8073964367",
    email: "Not available",
    majorCrops: ["Coconut", "Tomato", "Green Chilli"]
  },
  {
    sNo: 96,
    state: "Karnataka",
    district: "Belagavi",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Vivekanand Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01114KA2017PTC100701",
    registrationDate: "21.Feb.17",
    address: "Samudaya Kalika Kendra, Nirvahana, Beside Gram Panchayat, At & Post: Rajapur, Gokak, Belagavi, Karnataka, 591224",
    contactPerson: "Shivkumar I Gadagali",
    contact: "08310489785",
    email: "gokakfpo@gmail.com",
    majorCrops: ["Tomato", "Cabbage", "Turmeric"]
  },
  {
    sNo: 97,
    state: "Karnataka",
    district: "Mysuru",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Hamparura Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC100934",
    registrationDate: "28.Feb.17",
    address: "Hampapura Village and Post, Hirenandi H D Kote (TQ), Mysuru (Dist), Mysuru- 571125, Karnataka",
    contactPerson: "Mr. Trinesh",
    contact: "7406583069",
    email: "Not available",
    majorCrops: ["Tomato", "Beans"]
  },
  {
    sNo: 98,
    state: "Karnataka",
    district: "Mysuru",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Arkeshwara Swamy Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC101131",
    registrationDate: "07.Mar.17",
    address: "Senior Assistant Director of Horticulture, Horticulture office, K. R. Nagar, Mysuru (Dist), Mysuru- 571602, Karnataka",
    contactPerson: "Mr Shivakumar",
    contact: "8147827154",
    email: "Not available",
    majorCrops: ["Tomato"]
  },
  {
    sNo: 99,
    state: "Karnataka",
    district: "Dharwad",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Dummawad Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01110KA2017PTC101955",
    registrationDate: "05.Apr.17",
    address: "#132, Near Bus Stand, G. Basavana, Kalaghatagi (TQ), Dharwad (Dist), Dharwad- 580114, Karnataka",
    contactPerson: "Mr Basavaraj",
    contact: "9483475850",
    email: "Not available",
    majorCrops: ["Mango"]
  },
  {
    sNo: 100,
    state: "Karnataka",
    district: "Mandya",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "International Competence Centre for Organic Agriculture (ICCOA)",
    fpoName: "Honnalagere Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC101256",
    registrationDate: "10.Mar.17",
    address: "#07, Dagada, K Honnalagere, Kasab, Madduru (TQ), Mandya (Dist), Mandya- 571433, Karnataka",
    contactPerson: "Ms Chandani",
    contact: "9535803883",
    email: "Not available",
    majorCrops: ["Banana", "Tomato"]
  },
  {
    sNo: 101,
    state: "Karnataka",
    district: "Hassan",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Indian Grameen Services (IGS)",
    fpoName: "Sri Chennambika Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01113KA2016PTC098805",
    registrationDate: "27.Dec.17",
    address: "C/o PACCS Mosalehosalli, Mosalehosalli (P), Hassan Tq, Hassan- 573212, Karnataka",
    contactPerson: "Mr. Deekshith",
    contact: "8660571200",
    email: "srichennmika@gmail.com",
    majorCrops: ["Potato", "Maize", "Coconut"]
  },
  {
    sNo: 102,
    state: "Karnataka",
    district: "Haveri",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Indian Grameen Services (IGS)",
    fpoName: "Kumadwati Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01110KA2017PTC101395",
    registrationDate: "05.Mar.17",
    address: "VSN Complex, Near Old Bus Stand, Rattihalli, Haveri- 581116, Karnataka",
    contactPerson: "Mr. Nagesh Keri",
    contact: "9513319082",
    email: "nsk240@gmail.com",
    majorCrops: ["Maize", "Cotton", "Cabbage", "Chilli"]
  },
  {
    sNo: 103,
    state: "Karnataka",
    district: "Haveri",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Indian Grameen Services (IGS)",
    fpoName: "Byadagi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC105444",
    registrationDate: "09.Aug.17",
    address: "Sri Vinayaka Complex Opp Government Chikkabasur At and Post, Byadagi Taluk, Haveri- 581120, Karnataka",
    contactPerson: "Vijay Kumar",
    contact: "9986740172",
    email: "Not available",
    majorCrops: ["Arecanut", "Banana", "Cotton", "Maize"]
  },
  {
    sNo: 104,
    state: "Karnataka",
    district: "Shivamogga",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Indian Grameen Services (IGS)",
    fpoName: "Sharavathi Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC108227",
    registrationDate: "27.Nov.17",
    address: "S/O Gangadharappa No. 71 Mayathana, Near Government School Sunnadakoppa Shikaripura, Shivamogga- 577428, Karnataka",
    contactPerson: "Ravikumar, NG",
    contact: "9164648861",
    email: "Not available",
    majorCrops: ["Arecanut", "Banana", "Ginger"]
  },
  {
    sNo: 105,
    state: "Karnataka",
    district: "Kolar",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "MYRADA",
    fpoName: "Holur Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC101507",
    registrationDate: "20.Mar.17",
    address: "Holur, Kolar-563126, Karnataka",
    contactPerson: "Mr. Mohammed Imran Khan",
    contact: "9916653069",
    email: "fpokolar@gmail.com",
    majorCrops: ["Mango", "Tomato", "Vegetables"]
  },
  {
    sNo: 106,
    state: "Karnataka",
    district: "Kalaburagi (Gulbarga)",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "MYRADA",
    fpoName: "Grameena Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01110KA2017PTC101233",
    registrationDate: "09.Mar.17",
    address: "#MIG 2, MSK Mill Road, Shanthinagar, Bahamanipura Post, Kalaburagi- 585103, Karnataka",
    contactPerson: "Mr. Parameshwar",
    contact: "7619280624",
    email: "fpokamalapur@gmail.com",
    majorCrops: ["Onion", "Banana"]
  },
  {
    sNo: 107,
    state: "Karnataka",
    district: "Chitradurga",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "MYRADA",
    fpoName: "Vanivilasa Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC101734",
    registrationDate: "27.Mar.17",
    address: "Temple Street, Saraswathi Complex, Hiriyur, Chitradurga- 577598, Karnataka",
    contactPerson: "Mr. Vivek",
    contact: "7619102697",
    email: "hiriyurfpo@gmail.com",
    majorCrops: ["Pomegranate", "Coconut"]
  },
  {
    sNo: 108,
    state: "Karnataka",
    district: "Yadgir",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "MYRADA",
    fpoName: "Revanasiddeshwara Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC103122",
    registrationDate: "19.May.17",
    address: "# 8, Revanasiddeshwara Nilay, Chamnal, Shahapur- (Tq), Yadgir, Karnataka, 585309",
    contactPerson: "Mr. Vivekanand",
    contact: "9901124056",
    email: "shahapurfpo@gmail.com",
    majorCrops: ["Brinjal", "Green Chilli", "Okra/Ladyfinger", "Tomato"]
  },
  {
    sNo: 109,
    state: "Karnataka",
    district: "Kalaburagi (Gulbarga)",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "MYRADA",
    fpoName: "Sangamanath Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC104336",
    registrationDate: "03.Jul.17",
    address: "#72, Gowdagoun, Kognur, Afzalpur (Tq), Kalaburagi- 585213, Karnataka",
    contactPerson: "Mr. Shivakumar",
    contact: "9902070282",
    email: "afzalpurfpo@gmail.com",
    majorCrops: ["Banana", "Lemon", "Onion"]
  },
  {
    sNo: 110,
    state: "Karnataka",
    district: "Ballari",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "MYRADA",
    fpoName: "Anjanadri Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC108406",
    registrationDate: "04.Dec.17",
    address: "Horticulture Dept Premises, Main Rd, Basaveshwara Circle, Hagribommanahalli, Ballari- 583212, Karnataka",
    contactPerson: "Mr. Shivaraj",
    contact: "6361971493",
    email: "ajanadrihfpo@gmail.com",
    majorCrops: ["Coconut", "Mixed Vegetables", "Pomegranate"]
  },
  {
    sNo: 111,
    state: "Karnataka",
    district: "Vijayapura (Bijapur)",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Bijapur Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01114KA2017PTC102020",
    registrationDate: "06.Apr.17",
    address: "Takkalaki, Bijapur Rsd, Vijayapura- 586104, Karnataka",
    contactPerson: "Mr. Yellappa",
    contact: "8904618176",
    email: "Not available",
    majorCrops: ["Grapes", "Pomegranate", "Vegetables"]
  },
  {
    sNo: 112,
    state: "Karnataka",
    district: "Vijayapura (Bijapur)",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Basavanbagewadi Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01110KA2017PTC102024",
    registrationDate: "06.Apr.17",
    address: "Nidagundi, Bagewadi, Vijayapura- 586216, Karnataka",
    contactPerson: "Mr. Jagdish",
    contact: "9845068960",
    email: "Not available",
    majorCrops: ["Grapes", "Onion", "Pomegranate"]
  },
  {
    sNo: 113,
    state: "Karnataka",
    district: "Koppal",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Yelburga Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC103740",
    registrationDate: "09.Jun.17",
    address: "C/o Basappa Bavi, Muradi, Koppal- 583237, Karnataka",
    contactPerson: "Mr. Rudregowda",
    contact: "9535010733",
    email: "Not available",
    majorCrops: ["Onion", "Papaya", "Pomegranate"]
  },
  {
    sNo: 114,
    state: "Karnataka",
    district: "Bidar",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Bidar Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2017PTC108910",
    registrationDate: "22.Dec.17",
    address: "C/o Srinivas, S/o Devendra Natekar, CMC No. 17-4-372/46 Kashibai Layout, Gumppa, Bidar- 585401, Karnataka",
    contactPerson: "Mr. Jeetendar Holkar",
    contact: "8884745627",
    email: "Not available",
    majorCrops: ["Ginger", "Mango"]
  },
  {
    sNo: 115,
    state: "Karnataka",
    district: "Raichur",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Lingasur Horticulture Farmer Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01113KA2017PTC108659",
    registrationDate: "14.Dec.17",
    address: "C/o Doddabasappa Pampanna Angad, 44, Ward No. 00, Upperi, Lingasugur, Raichur- 584122, Karnataka",
    contactPerson: "Mr. John Mudagal",
    contact: "9663299847",
    email: "Not available",
    majorCrops: ["Onion", "Pomegranate"]
  },
  {
    sNo: 116,
    state: "Karnataka",
    district: "Chamarajanagar",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "MYRADA",
    fpoName: "Kollegala Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01114KA2017PTC105229",
    registrationDate: "02.Aug.17",
    address: "Kollegala Horticulture Farmers Pro, Boodubalu Road, Mangala Post, Kollegal (Tq), Chamarajanagar- 571443, Karnataka",
    contactPerson: "Ms. Lalitha",
    contact: "9880224990",
    email: "myradahuthur@gmail.com",
    majorCrops: ["Banana", "Maize", "Onion", "Turmeric"]
  },
  {
    sNo: 117,
    state: "Karnataka",
    district: "Bagalkot",
    programme: "Special Project (Phase-II)",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Hungunda Horticulture Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01113KA2018PTC114434",
    registrationDate: "03.Jul.18",
    address: "C/o Basayya Sangayya Nanjayyanath, Sulebhavi, Hungund, Bagalkot- 587124, Karnataka",
    contactPerson: "Mr. Dholappa Tamaddi",
    contact: "9008640862",
    email: "Not available",
    majorCrops: ["Onion", "Lemon", "Red Chilli", "Red Gram"]
  },
  {
    sNo: 118,
    state: "Karnataka",
    district: "Shivamogga",
    programme: "KSSDB",
    resourceInstitution: "Indian Society of Agribusiness Professionals (ISAP)",
    fpoName: "Shodha Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01110KA2017PTC104259",
    registrationDate: "29.Jun.17",
    address: "No. 265/291, Near Canara Bank, Po Nittur, Tq Hosanagara, Shivamogga- 577452, Karnataka",
    contactPerson: "Mr. Vishu Kumar",
    contact: "9570641536",
    email: "Not available",
    majorCrops: ["Pepper", "Ginger", "Arecanut"]
  },
  {
    sNo: 119,
    state: "Karnataka",
    district: "Chamarajanagar",
    programme: "KSSDB",
    resourceInstitution: "MYRADA",
    fpoName: "Souharda Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2018PTC110216",
    registrationDate: "17.Feb.17",
    address: "Attugulipura Village, Sathy Main Road, Chamarajanagar- 571127, Karnataka",
    contactPerson: "Mr. Suresh Kumar",
    contact: "9986534362",
    email: "myradahuthur@gmail.com",
    majorCrops: ["Banana", "Turmeric"]
  },
  {
    sNo: 120,
    state: "Karnataka",
    district: "Kalaburagi (Gulbarga)",
    programme: "NFSM-Nutri-Cereals (Millets)",
    resourceInstitution: "MYRADA",
    fpoName: "Hirodeshwara Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2019PTC125914",
    registrationDate: "05.Jul.19",
    address: "7/221, Shiva Nilaya, Main Road Bhankur, Opposite Sevalal Complex, Shanth Nagar, Shahabad, Kalaburagi- 585228, Karnataka",
    contactPerson: "Mr. Guru P H",
    contact: "9538428265",
    email: "bhankurfpo@gmail.com",
    majorCrops: ["Jowar", "Millets"]
  },
  {
    sNo: 121,
    state: "Karnataka",
    district: "Bagalkot",
    programme: "NFSM-Nutri-Cereals (Millets)",
    resourceInstitution: "ICAR-IIMR",
    fpoName: "Greens Millet Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01100KA2020PTC132969",
    registrationDate: "24.Feb.20",
    address: "Plot No- 50, Kiada, Bagalkot- 587103, Karnataka",
    contactPerson: "Sidling Sajjan",
    contact: "9686991848",
    email: "Not available",
    majorCrops: ["Millets"]
  },
  {
    sNo: 122,
    state: "Karnataka",
    district: "Ramanagara",
    programme: "NFSM-Nutri-Cereals (Millets)",
    resourceInstitution: "MYRADA",
    fpoName: "Kodihalli Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01110KA2020PTC141465",
    registrationDate: "25.Nov.20",
    address: "House No. 64, MNS Road, Kanakapura Town, Ramanagara- 562117, Karnataka",
    contactPerson: "Mr. Tajuddin",
    contact: "9739056643",
    email: "mail2tajuddin@gmail.com",
    majorCrops: ["Ragi"]
  },
  {
    sNo: 123,
    state: "Karnataka",
    district: "Koppal",
    programme: "NFSM-Nutri-Cereals (Millets)",
    resourceInstitution: "Indian Institute of Millets Research (IIMR)",
    fpoName: "Koppal Millet Farmers Producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01400KA2020PTC142221",
    registrationDate: "15.Dec.20",
    address: "4/100 Ward number 3rd Floor near market, Irkagada Taluk, Koppal- 583237, Karnataka",
    contactPerson: "Dr Sangappa",
    contact: "9880045728",
    email: "Not available",
    majorCrops: ["Millets"]
  },
  {
    sNo: 124,
    state: "Karnataka",
    district: "Vijayapura (Bijapur)",
    programme: "NFSM-Nutri-Cereals (Millets)",
    resourceInstitution: "MYRADA",
    fpoName: "Shri Somanatheshwara Farmers producer company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01409KA2021PTC142981",
    registrationDate: "09.Jan.21",
    address: "ASKI, Sindgi TQ, Vijayapura- 586118, Karnataka",
    contactPerson: "Mr Siddhu patil",
    contact: "9740483129",
    email: "Not available",
    majorCrops: ["Jowar", "Millets"]
  },
  {
    sNo: 125,
    state: "Karnataka",
    district: "Vijayapura (Bijapur)",
    programme: "NFSM-Nutri-Cereals (Millets)",
    resourceInstitution: "MYRADA",
    fpoName: "Sree Madivaleshwara Farmer producer Company Limited",
    legalForm: "Producer Company",
    registrationNumber: "U01110KA2021PTC143935",
    registrationDate: "11.Feb.21",
    address: "Zalaki Building Near Police Station, Kalakeri Talikoti, Vijayapura- 586118, Karnataka",
    contactPerson: "Mr. Tajuddin",
    contact: "9739056643",
    email: "mail2tajuddin@gmail.com",
    majorCrops: ["Jowar", "Millets"]
  }
];

const SOURCE_URL = "https://sfacindia.com/PDFs/List-of-FPO%20identified-by-SFAC/List%20of%20FPOs%20in%20the%20State%20of%20Karnataka.pdf";
const PORTAL_URL = "https://sfacindia.com/FPOS.aspx";
const SOURCE_NAME = "Small Farmers' Agri-Business Consortium (SFAC), Dept. of Agriculture & Farmers Welfare, Govt. of India";

const processedFpos = RAW_DATA.map((item) => ({
  id: `sfac-ka-${item.sNo}`,
  sNo: item.sNo,
  state: item.state,
  district: item.district,
  fpoName: item.fpoName,
  legalForm: item.legalForm,
  registrationNumber: item.registrationNumber,
  registrationDate: item.registrationDate,
  address: item.address,
  contactPerson: item.contactPerson,
  contact: item.contact,
  email: item.email,
  majorCrops: item.majorCrops,
  programme: item.programme,
  resourceInstitution: item.resourceInstitution,
  sourceName: SOURCE_NAME,
  sourceUrl: SOURCE_URL,
  portalUrl: PORTAL_URL,
  sourceUpdatedDate: "Official SFAC Published Directory",
  verificationStatus: "Government Listed",
  onlineStatus: "Unknown",
  communityStatus: "NOT CONNECTED"
}));

const outPath = path.resolve('src/data/karnatakaFposData.json');
fs.writeFileSync(outPath, JSON.stringify(processedFpos, null, 2), 'utf-8');
console.log(`Successfully generated ${processedFpos.length} official Karnataka FPO records to ${outPath}`);
